language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

before_install:
  - chmod +x gradlew

env:
  global:
    - secure: "qrp8BdAVimd1fz0326AASo8ffHVS+pEZnGc+nfLWImdxX7B3CNqOIomlNMmk7ToR75I88l37cIwIqevJgvVlEbe7SfdXbSKR3BF3L6Mtgn6O3PKlpie+pgDg7jxgdfKzKNtFcrOBiRpR0zrF22nBy3JEAypGpsNqtcleqT5f8ZOQNZhNzrOjALfJVf0SsfrrMAQqEgJcyT9aTPlDIdJzbPBpMfoI87kMZ4N74qkfzgQsPmO1yX4XbcqIF1skD0EfRw2DmdTC3ZNIAdKsicEmyWAAG0pw3irpZ4VFgZLYueZTDXhVXnJBxRkkengkpyz279OM4m1KkspFOPOQYXpIzHTovvPQjdZ4SNt4Po/+P5LKnbra4l/15podaDwPcOgBlZtrCFQcNUMrT/dFCBZ9jVvrUBuDDI8Q9xQgeHTxWdx3On44MKKSsQ+JK50u3L2oOgONMIzROUA8sla/CGrSQj90WzRPg4aTMK/N9EJmeCUP/FexoYFCXWmpOO/+UHyLXnGAM3EPhiXGv6N/hhLWO3gfKHMNHOFgErxDxZx39hjsVvSfgwBlptRnvF4p428lOhXCKLVtJtHGVPhQaBjs0m7q4ZAKLwzG6HXHKINrfNzja89DozlykTpkVM32GRORtIan9ZfDtAES30bM6VPuAEPO+H7wPwZ8Y8X/g/UlaSE="
    - secure: "Qhl8jiBT3jb+Fpe+kAhFZGctEPCNdwR3zDsroJOY+RaxW9BaSPXaM5XcqAWnIAtIxNhFw2TaWGbh+QKqcHGzD+Ay6R/2Q8xEYR6NMWuVlOlSC03Xa89z1zf6AfpfMh/aa+iVrI5HvV97KzX5U++xEgSRNW/cdhMkEKq12pgWYzwTKyiio++rLVH3YjvBY7q7WA46DJqils6+5GnHYuKeM/VW9LD0L7BSdLpZ2VtUtl6VDAJrubOLgl0iKTkKDvqwtDTjaep26yswY4gf+Wr4r/XhcRCeyNTktl85CoHb1efJ92mm3lEt0zOIliJqbPRKmU1oYJHLi22E3y0xgbEFEfcMxejIMi9mxf7JudRE0z6AtAq2VAvJm+KnVVhoC7pETmoU4CAH9vtjqpX0JHcETrcagTjD3HCRcO7gSUE05NkVpHmEp7Dok+HacZN44yuVfcErwAQ3ehI5ou8uGbkRVG/ZW6WtR2y1AK7SHlxekjyY3rjL18ZgNgFAeSHf1QGXysPLV7sCSkdw+xxFpXiq8W8YtqpEIu0mYptSz6J0TQADKAbGaRP+GGzobfspqbV173C6u0uBM4UmI/49yepobFzaQrqlEZoXT6Xcf6SzZYPMuZeGJkzUeYPkV0jLEN7I4HEqJQF8SElw88Zer1K7ShP0IlcnrlEAh5Gf6KTHOec="

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish
    on:
      branch: master
      jdk: oraclejdk8
  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload
    on:
      tags: true
      jdk: oraclejdk8